### ISSUE TITLE
Change image name to ghcr.io/kedacore/keda-external-scaler-azure-cosmos-db

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda-external-scaler-azure-cosmos-db#12]
Change image name to ghcr.io/kedacore/keda-external-scaler-azure-cosmos-db to emphasize that it's an external scaler.

Follow-up for #10

**Comment by tomkerkhove** [comment]
Added a task for it @JatinSanghvi

**Comment by JatinSanghvi** [comment]
I had discussed my intention to change the package name with Pragna. Created PR #13 to address the issue. Please delete package `keda-cosmosdb-scaler` once the PR is completed.
