### ISSUE TITLE
Update externalscaler.proto to follow protobuf style guidelines

### ISSUE THREAD

**Issue by divyagandhisethi** [kedacore/keda-external-scaler-azure-cosmos-db#5]
External scaler.proto should follow the style guidelines from here- https://developers.google.com/protocol-buffers/docs/style .  This will be a breaking change and needs to be updated as part of major version upgrade.

**Comment by tomkerkhove** [comment]
I think this is more a suggestion for KEDA core, right @pragnagopa?

**Comment by pragnagopa** [comment]
> I think this is more a suggestion for KEDA core, right @pragnagopa?

Yes - should be part of Keda core. Consider updating in the next major version.

**Comment by JatinSanghvi** [comment]
Created bug https://github.com/kedacore/keda/issues/2096 on keda repo. @tomkerkhove, this one can be closed.
